name: main

on:
  push:
    branches:
      - main
      - debug

env:
  DOCKER_IMAGE: chuhlomin/render-template

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to CR
        uses: docker/login-action@v2
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:debug

      - name: Test action
        uses: ./ # Uses an action in the root directory
        id: render
        with:
          template: ./testdata/template_debug.txt
          vars: |
            name: world

      - name: Get `result_from_entrypoint` output
        run: echo "${{ steps.render.outputs.result_from_entrypoint }}"

      - name: Get `result` output
        run: echo "${{ steps.render.outputs.result }}"
