name: main

on:
  push:
    branches:
      - main
      - debug

env:
  DOCKER_IMAGE: chuhlomin/render-template

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to CR
        uses: docker/login-action@v1
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:debug
          labels: ${{ steps.meta.outputs.labels }}
